### ISSUE TITLE
Improve error/warning colors in Console's dark theme

### ISSUE THREAD

**Issue by violasong** [devtools-html/ux#12]
In dark mode, the warning messages look way brighter than the error messages, but errors should have equal (or more) visual priority. (The colors are lighter versions of the [Photon palette](https://design.firefox.com/photon/visuals/color.html), but could use improvement.)

<img width="468" alt="image" src="https://user-images.githubusercontent.com/55994/44435360-831f9d80-a564-11e8-95e0-d415609a9d32.png">

**Comment by natashahockey** [comment]
I'd like to claim this issue for my first UX task 👍

**Comment by violasong** [comment]
Sounds good! One thing I forgot to mention - we're in the process of improving color contrasts in dark mode, so for this task it would be better to lighten the error color rather than darker the warning color

**Comment by natashahockey** [comment]
Awesome, I've put together a quick mockup in Sketch. I don't have the correct font you use, so I've gone with Menlo for now. I've used the colour Yellow 60 #d7b600 from the design system to make it darker. Look forward to hearing your feedback on this :)

<img width="783" alt="error warning colour" src="https://user-images.githubusercontent.com/15910006/44618952-8f16a280-a877-11e8-8cd9-64accaee4bc5.png">

**Comment by martinbalfanz** [comment]
I quickly applied the suggested color and I think it looks good!
<img width="191" alt="screen shot 2018-08-27 at 11 36 56" src="https://user-images.githubusercontent.com/653763/44652952-a24b7e80-a9ed-11e8-9017-421da0dda206.png">

BTW: I believe Menlo is the correct font 🙂

**Comment by natashahockey** [comment]
Awesome! Glad you’re happy with the suggested solution 😀

**Comment by violasong** [comment]
Hi Natasha, thanks for this work! I was actually thinking it would be best to change the red text color to be brighter, rather than changing the yellow color to be darker. Sorry for the confusion!

It could be nice to get the red [contrast ratio](http://accessible-colors.com/) to 6:1 or above to match other work on raising contrast.

**Comment by bwinton** [comment]
I thought we switched to `San Francisco` for the macOS font...

@natashahockey: In theory, you should be able to download all the fonts from links off of [the Design System](https://design.firefox.com/photon/visuals/typography.html). Please let me know if that doesn't work!

**Comment by martinbalfanz** [comment]
@bwinton `San Francisco` in general yes, but not as monospaced font (e.g. for the Console).

For reference from our source code:
```css
:root[platform="mac"] {
  --monospace-font-family: Menlo, monospace;
}

:root[platform="win"] {
  --monospace-font-family: Consolas, monospace;
}

:root[platform="linux"] {
  --monospace-font-family: monospace;
}
```

**Comment by fvsch** [comment]
It seems we have updated colors for errors and warnings in the dark theme nowadays (we aligned them with Photon in a few different bugs).
@violasong, are these okay and can we close this issue, or should we update them?

<img width="660" alt="screenshot" src="https://user-images.githubusercontent.com/243601/49815688-a026e900-fd6c-11e8-92ec-7e64844423cc.png">

**Comment by violasong** [comment]
Yes, this is done — thanks for the nice fix for this!
