### ISSUE TITLE
Debugger - Visibility difficulty for file name in call stack 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/ux#17]
Debugger [Issue](https://github.com/devtools-html/debugger.html/issues/6374)

Screenshot taken from Nightly:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/1588648/40332480-da62bb92-5d19-11e8-86ae-5dd59ab49103.png">

I have trouble reading this text with my glasses. Any smudges on my lenses or chromatic aberration at the edges of my glasses makes it very difficult to read.

**Comment by violasong** [comment]
Thanks Jason! 

Some extra background info on this problem: https://github.com/devtools-html/debugger.html/issues/6374

**Comment by natashahockey** [comment]
Happy to take a look at this issue. Will post a solution later today :)

**Comment by natashahockey** [comment]
@jasonLaster Would you mind explaining how I would recreate this please?

**Comment by jasonLaster** [comment]
So, it should be possible to pause in the firefox debugger and see the call stack. If you'd like to easily work on it you can follow our getting started steps here: https://github.com/devtools-html/debugger.html/

**Comment by yogmel** [comment]
Hi people!
Having a look at the Call Stack on the Debugger tabs, it looks like the font-weight is set to light (100), as @violasong has pointed out.

That being said, I have tested setting it to normal. Does it look ok to you?
![00](https://user-images.githubusercontent.com/3901809/45987966-ac8f8580-c04a-11e8-86d6-4712b9956e93.PNG)


The selector for this style is .frames .location, in the file debugger.css:3448
![image](https://user-images.githubusercontent.com/3901809/45987990-cb8e1780-c04a-11e8-8ef4-69d078bfd99c.png)

**Comment by yogmel** [comment]
Hi @violasong! Just letting you know I've made the PR. If there is anything you would like me to change, please feel free to contact me!

**Comment by violasong** [comment]
Great work @yogmel! Sorry for the delay - I see your work was merged and committed, so I will close this bug :).
