### ISSUE TITLE
Better Callstack Frame groups

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/ux#34]
In the debugger, the callstack panel detects when frames originates from a library and group them together in order to give the user a more digest callstack (the code they're interested in is most likely *not* in the library/framework source).
Here's how it looks: 

<img width="355" alt="image" src="https://user-images.githubusercontent.com/578107/47431928-460e9c00-d79d-11e8-8316-00bd6aa32a9b.png">

It shows the last frame of the group, and the framework/library with an icon (here React).
It also shows the number of grouped frames in a badge.
The user can still click on the group to have all the frames revealed: 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/578107/47432043-866e1a00-d79d-11e8-96db-42a848b70771.png">

---

I feel like we could do a better job to represent this.
It's not really clear that I can click on the group to reveal its content.
Also, the Badge is not really helpful here:
- is there value showing how many frames were hidden ?
- why is it next to the function name ? (one could be confused in thinking the function was called N times, since we do have this badge representation in the console, where it indicates a log was issued multiple times).

For now, the only reason I would keep the badge is because it make this given frame stand out from the other (regular) ones, but we could think of ways to make that better.

---

Some things to consider: 
- there's limited horizontal & vertical space available in the callstack panel in the debugger
- this component might get used in other places than the debugger (e.g. console), where we do have more space

**Comment by nchevobbe** [comment]
Let's go with a naive thing: we could have a text to expand/collapse the group: 

```
App                                  App.js:7
indeterminateComponent               React
<show all react frames>
eval                                 index:6
```

we already have a similar mechanism in this panel (by default, we only show the last 7 frames):

<img width="287" alt="image" src="https://user-images.githubusercontent.com/578107/47432683-0d6fc200-d79f-11e8-8009-8c7ede0a5132.png">

once expanded, you can collapse them: 

<img width="281" alt="image" src="https://user-images.githubusercontent.com/578107/47432730-28dacd00-d79f-11e8-91db-729003b95145.png">

---

so we could copy that to allow to expand/collapse a given group

**Comment by nchevobbe** [comment]
We could also only display the framework name and icon, with a triangle (as its something we have everywhere in devtools): 

```js
App                                  App.js:7
▶︎ React ⚛️
eval                                 index:6
```

```js
App                                  App.js:7
▼ React ⚛️
|    IndeterminateComponent
|    beginWork
|    performUnitOfWork
eval                                 index:6
```

It depends on how useful we think it is to show the last frame of a group.

**Comment by fvsch** [comment]
Two other variants:

```
App                                  App.js:7
indeterminateComponent               React
  ↳ 17 more frames in group
eval                                 index:6
```

(With the "17 more..." line acting as a button to reveal collapsed frames.)
I like it but if we have several collapsed groups, we're going to have a lot of repetition.

So maybe something compact like:

```
  App                                App.js:7
▶︎ indeterminateComponent (+17)       React
  eval                               index:6
```

Not sure we need the arrow. The "(+N)" pattern may be enough to suggest that there is extra content, and to differentiate from the console count badge (especially if we use a different design, something less badge-like).

**Comment by nchevobbe** [comment]
See how this could be done in the debugger: 

Collapsed:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/578107/47557943-441a1980-d912-11e8-9845-0f49673122c1.png">

Expanded: 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/578107/47557978-5b590700-d912-11e8-9ec1-c41d5c7ace35.png">

**Comment by nchevobbe** [comment]
With the `+N` text: 

<img width="390" alt="image" src="https://user-images.githubusercontent.com/578107/47558493-8ee86100-d913-11e8-90fb-08bd17b883cd.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/578107/47558533-a7f11200-d913-11e8-8393-2e63e6557201.png">

**Comment by nchevobbe** [comment]
One thing to note, in the last screenshot, I modified the Group code to not show the last frame *in( the group when it is expanded.

At first this sounds reasonable, but now I see an issue: clicking on `callCallback` only toggle the group, and as a result, we can't navigate to `callCallback`.

Which might help us in our task here. For me it feels weird that we are displaying something which looks very similar to the other frames, but does not have the same action when you click it. And then it appears twice when you expand the group: 
<img width="466" alt="image" src="https://user-images.githubusercontent.com/578107/47558938-90feef80-d914-11e8-9e34-fb960ff755bd.png">

This is why, for now, I'd prefer to only have the Group name, with a distinct style so it's more clear what's happening (See https://github.com/devtools-html/ux/issues/34#issuecomment-433347621)

@darkwing @loganfsmyth @jasonLaster I'd love to know what you think about this.

**Comment by fvsch** [comment]
I like the one with `firstFrame (+N)` in https://github.com/devtools-html/ux/issues/34#issuecomment-433350259

It's indeed missing a visual indicator that this is an expandable header, so we could have a twisty icon on the left: `▶︎ firstFrame (+N)`

But there's a risk this could be confused with headers.

One way to differentiate, beyond the header borders and background, would be to make sure that header text is using the "bigger" 12px font-size, and the section content is using the standard 11px font-size. With a more compact design for frames, as discussed in https://github.com/devtools-html/ux/issues/3, and 11px text, we may have better visual hierarchy:

<img width="347" alt="screenshot" src="https://user-images.githubusercontent.com/243601/47580415-215a2600-d94f-11e8-9efe-fcb62cc0f00b.png">

Adding a ▶︎ icon in that some rows' left gutter should work alright, then.
Pinging @mcroud if you have some time to look at this in the future.

**Comment by jasonLaster** [comment]
Perhaps another comparison is how chrome shows async boundaries in the call stack
`-- setTimeout --` or whatever.

One other thought, which was never really acted on is that we want to know what the group is
e.g. `_renderValidatedComponentWithoutOwnerOrContext` -> 'Rendering'

here are the current mappings. I think we could do a better job of adding more mappings too and in the future let web extensions do this

https://github.com/devtools-html/debugger.html/blob/master/src/utils/pause/frames/displayName.js#L43-L68

**Comment by nchevobbe** [comment]
Here's the an example of what chrome does, in console
<img width="252" alt="image" src="https://user-images.githubusercontent.com/578107/47728826-676cfd80-dc5f-11e8-9899-5d04f445305e.png">

and in debugger: 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/578107/47728956-9f744080-dc5f-11e8-89e8-bd6d19c91b47.png">


So I guess what Jason is saying is that we could have 
```
App                      App.js:7
---------- ▶︎ React ⚛️ -------------
eval                     index:6
```

and then

```
App                      App.js:7
---------- ▼ React ⚛️ -------------
react3
react2
react1
----------------------------------
eval                     index:6
```

I guess ?

**Comment by jsomedon** [comment]
Just saw you mentioning this on slack channel, so here is opinion coming from someone just started playing with debugger.html couple days ago with extremely limited experience about firefox devtools, and js debugging in general.

The ▶︎ is already used for expanding "Watch expressions" and "Breakpoints" tabs (actually, how do you guys call this, tab? section?) so if I see ▶︎ for grouped frames, my instinct tells me that:

> oh this is another "tab" just like "Watch expressions" or "Breakpoints", but it's under "Call stack" tab, so what is it, a sub-tab?

I actually like the the point of using a special symbol to hint user that "this item is expandable into more items". Maybe using symbol + instead? Or symbol >?

I also like the `↳ N more frames in group` in example above. Too verbose, too many lines? Then maybe just add "grouped" label after frame name? What about just "..." after frame name?

So might be like:
```
  top frame
> middle frame...
  bottom frame
```
you click `>` and it becomes `v` and expands:
```
  top frame
v   middle frame a
    middle frame b
    middle frame c
  bottom frame
```

**Comment by fvsch** [comment]
> so if I see ▶︎ for grouped frames, my instinct tells me that (…)

For comparison's sake, we already use this symbol for expandable content in panel content, not just panel headers. See the Inspector (markup view, Rules, Layout>Box Model, Fonts) and Console (for collapsed errors, objects, and network requests).

**Comment by mcroud** [comment]
Could someone provide me with steps to generated a prime example of this, where I can see I hefty grouped library of frames and with additional, non-grouped items?

**Comment by nchevobbe** [comment]
You can go to https://nchevobbe.github.io/demo/console-test-app.html , and then
1. Open the debugger
1. Search for the `reducers.js` file
1. Add a breakpoint on in `handleLog` (e.g. on `if (action.data)`)
1. In the content page, scroll to the bottom, and in the "React/Redux" section, click on the "trace" button <img width="757" alt="image" src="https://user-images.githubusercontent.com/578107/48128717-93a00400-e287-11e8-8ee4-6c68ea098f3c.png">
1. You should get the following in the callstack panel 
<img width="308" alt="image" src="https://user-images.githubusercontent.com/578107/48128738-a9152e00-e287-11e8-973d-63d31af14556.png">

**Comment by nchevobbe** [comment]
Hello @mcroud , did you get a chance to experiment with this?
Since we're shipping the SmartTrace in console in 65, it would be nice if we could have the new design at the same time :)

**Comment by nchevobbe** [comment]
(also, we got a bug report for the console about the badge being confusing, which indicates that something needs to be done for this element)

**Comment by mcroud** [comment]
@nchevobbe I haven't I'm afraid :( I can give time to this on Monday and have something to show at the end of Monday, is that too late?

A few comments based on the discussion so far:

I would be keen on first exploring ideas which avoid using a collapse/expand triangle first to avoid confusion with pane headers. When expanded, if we are giving the group a light grey background it looks to have the same visual heirarcy to that of the parent "Call Stack" panel header.
I'm not ruling out the triangle though, as mentioned above it represents a common behaviour in devtools already.

Just to clarify, when we say badge do we mean the react icon or the number of how many frames are in the group?

I agree that showing a group name, as opoosed to the last frame as the group header would prevent the repitition of frame names and help differentiate the group from the other, singular entries in the list.

**Comment by nchevobbe** [comment]
> Just to clarify, when we say badge do we mean the react icon or the number of how many frames are in the group?

sorry, I meant to say the element with how many frames are in the group (e.g `(18)`)

**Comment by mcroud** [comment]
I found some time today to produce some visuals.
Take a look at A, B, C and D in the mockup. the designs use a mix of existing behaviours. Despite my earlier concerns with using the arrows, when accompanied with some inset spacing I think it's absolutely a solid choice. 

https://mozilla.invisionapp.com/share/34P9W25EV8K#/333068574__ (Invision)

![callstack-frames_2x](https://user-images.githubusercontent.com/42435754/48954001-ab41e280-ef3f-11e8-8a82-df5ad24bc9e0.png)

Which do you think works best ?

**Comment by fvsch** [comment]
Hard to say, I like them all. I'd say they're all solid choices.

Other than that:

- Just a detail: in all mock-ups, the `handleLog` line should not be highlighted in the second step (D is correct, A-B-C are not).

- For the collapsed state, visually my favorite is A. I don't mind not having the frame count, since the point is to hide frames that are not relevant for users ("this is library code and you're probably not interested in it"). The centered line also reminds me of some code collapsing indicators, so together with the "..." button it's a strong-enough indication that some content was collapsed here, at least for me. And given we want to de-emphasize library code, maybe we should use a normal font-weight instead of bold for the "Redux" and "React" labels (A and B).

- I think in the expanded state we should have indentation of the group frames (B, C and D). I'm not against the left border (C), but I think we can manage without it, and it simplifies the CSS implementation a bit (since we want the border to live inside the row, as shown by the highlighted row in C).

- In the expanded state, I think it's best to keep the ability to collapse the group again (B, C, D). We could have that in A as well, keeping the group header and maybe highlighting the "..." badge as active (see the "grid", "flex" or "event" badges in the Inspector's markup view, when clicked).

So my preference would be to go with A for the collapsed state, and B/D for the expanded state (but keeping A's header).

**Comment by nchevobbe** [comment]
I agree a lot with @fvsch , A is the more attractive, and we also should keep a way to collapse those frames again.

One small visual nit on A would be to not run the horizontal line right to the border, but align its end with the end of the line number 

<img width="773" alt="image" src="https://user-images.githubusercontent.com/578107/48997818-79a06580-f151-11e8-8439-dcf631a8dd94.png">


Otherwise, it can feels that the `React` thing ends the callstack, and that what follows is something else.

Also agree on not having the library names bold.

**Comment by mcroud** [comment]
@fvsch This is what happens when you update a Sketch Symbol moments before exporting! Thank you for the concise feedback.

@nchevobbe Great! This gives me clear direction for the next iteration.

**Comment by violasong** [comment]
Hi Matt! I haven't been paying attention to this whole thread but hopefully you won't mind if I drop in with one quick idea for option A:

The centered line makes me think of separation due to how gray horizontal lines are used elsewhere in Devtools (e.g. Inspector Rules), so I'm wondering if we could do something else here. I guess the ellipsis icon may not be prominent enough without the line?

Maybe the ellipsis could be right next to the framework name? (I'm assuming that clicking the framework name also expands the list) 

Overall it's looking good :)

**Comment by mcroud** [comment]
@violasong Thanks for the feedback, I'll certainly take that point into consideration for the next mockup! Cheers.

**Comment by mcroud** [comment]
Taking **A** from the last batch and applying everyone's feedback I have produced another four variations.

@violasong In answer to your previous question, yes I see clicking on the framework name having the same affect as clicking the ellipses badge.

https://mozilla.invisionapp.com/share/34P9W25EV8K (Invsision)

Which feels right to you!

![callstack frame group 2_2x](https://user-images.githubusercontent.com/42435754/49096877-71d0e600-f263-11e8-98ce-0d0826d6d150.png)

**Comment by fvsch** [comment]
In order of preference:

1. B for the minimalist approach.
2. C for a visually richer approach. (A is similar and is okay too, but I slightly prefer C.)

**Comment by violasong** [comment]
Ah, interesting 😅 - my favorite is D, as I still see the vertically
centered gray/blue lines as too much of a departure from DevTools/Firefox
styles. If we just need to emphasize the expanded part, I think there are
other ways to do that with either more indent, disclosure arrow, etc.

**Comment by mcroud** [comment]
Another suggestion might be utilizing the other Photon arrow design (https://github.com/FirefoxUX/photon-icons/blob/master/icons/desktop/arrowhead-down-12.svg) as a sort of secondary disclosure arrow. Still recognizable yet different enough to avoid confusion with panel headers?

**Comment by violasong** [comment]
Ah, based on about:home I think that that chevron arrow is meant to be shown after the heading. I actually think using the standard DevTools disclosure arrow would be fine, and might make the ellipsis unnecessary -- looking back at your previous Nov 23 mockup, I think B looks great!

One more idea for tightening up the look - I think the rows seem a little tall compared to the size of the accordion header - If I understand correctly @fvsch's work on this suggested 24px headers and 20px rows (https://github.com/devtools-html/ux/issues/3) - it would be like 30% shorter than how it is currently, but maybe worth trying for this design?

**Comment by fvsch** [comment]
24px-tall rows might be doable too, if that seems to look better.
In https://user-images.githubusercontent.com/243601/44299674-12297d00-a2fb-11e8-87d5-d16786ec0062.png the "large content row" option is wrongly labelled, the single-line one is 24px and not 20px.

**Comment by nchevobbe** [comment]
do we have an agreement here? I'd love to work on that before the end of the year

**Comment by mcroud** [comment]
B from the 23 Nov batch seems to be a positive suggestion for everyone, I will also take into the mix Victoria's suggestion of implementing fvsch's new height values and provide a mockup which might be the last. Hopefully get this done today

**Comment by nchevobbe** [comment]
Thanks a lot Matt and all, no worries if it's not today or next week. I
think it won't take long to implement, so we're not in a hurry

**Comment by mcroud** [comment]
Here we are! I thought I would present two variations based on popular choices of row height, we have the 20px row height and 24px height here. Interestingly developers who saw these mockups over my shoulder voiced their preference for the more compact design A. 

[Invision](http://mozilla.invisionapp.com/share/3WPIPX39ADN#/335776861_Callstack_Frame_Group_3)

![callstack frame group 3_2x](https://user-images.githubusercontent.com/42435754/49669160-8749cb00-fa2e-11e8-8731-14f0a46d19fd.png)

**Comment by fvsch** [comment]
I tend to like the 24px version better (B), but it's interesting that developers may prefer more compact information.

Did you use a 12px or 11px font size? It seems currently most of the Debugger's right panes use 12px, while the Sources pane and source code are 11px. So I would probably try to use 11px here, and maybe 11px with 20px high lines will work nicely then.

I would also try to add 4px vertical padding before the first and last rows, and see if that works.

**Comment by mcroud** [comment]
As we have agreed on the method for grouping these callstacks frames, may I propose that we go ahead with the visuals depicted in Mockup A posted on the 7th December ?
We have ongoing discussions on type, padding and general pane design which are absolutely valid and I can't wait to have them cast in stone but perhaps extend beyond the reach of this issue?

**Comment by mcroud** [comment]
Actually @fvsch I recall you mentioned having a discussion with @violasong regarding 11px type in panels at the All Hands?  
I thought I might as well cast these ideas into the mix, so here are the above suggestions in comparison with the previous mockup A:

![callstack frame group 4_2x](https://user-images.githubusercontent.com/42435754/50095521-a2c28c00-020d-11e9-9d63-348d9a17f3d4.png)

**Comment by violasong** [comment]
That 11px one looks great! I think the filenames:line numbers may need to be updated to 11 as well?

**Comment by mcroud** [comment]
> I think the filenames:line numbers may need to be updated to 11 as well?

Oh yes, they should have been!

Thank you both for critique with these iterations, unless I have missed anything with the below are we happy with where we are?

Invision: https://mozilla.invisionapp.com/share/SPPOC5IH9V3#/337551056_Callstack_Frame_Group_5

![callstack frame group 5_2x](https://user-images.githubusercontent.com/42435754/50148830-6f393d80-02b1-11e9-98e4-41697af4162d.png)

**Comment by fvsch** [comment]
Looks perfect to me, and the annotations will be helpful for implementing this. :balloon:

**Comment by violasong** [comment]
Yep looks perfect to me too!

**Comment by mcroud** [comment]
Great! Thank you.
@nchevobbe looks like we're all happy here with the mockups above (18 Dec), let me know if you need any other measurements etc.  :)

**Comment by nchevobbe** [comment]
Thanks a lot all. I created https://github.com/devtools-html/debugger.html/issues/7555 to implement this, so I think we can now close the issue :)
