### ISSUE TITLE
Checkboxes where there should be radio buttons

### ISSUE THREAD

**Issue by kuba-orlik** [devtools-html/ux#6]
62.0b18 (64-bit) on Linux:

![menu_174](https://user-images.githubusercontent.com/2697916/44410967-c3335000-a565-11e8-95ea-ad196589ca27.png)
![menu_173](https://user-images.githubusercontent.com/2697916/44410971-c4fd1380-a565-11e8-920c-62cbcd90ccae.png)

As only one option can be picked at a time, those should be radio buttons, not checkboxes

**Comment by birtles** [comment]
This should be fixed in 63 where we have new doorhanger-style menus.

**Comment by violasong** [comment]
Hooray!! Marking as closed :D

**Comment by ilmoralito** [comment]
This is my experience using firefox 16.04

![screenshot from 2018-08-21 18-48-23](https://user-images.githubusercontent.com/928920/44438000-642c0600-a57a-11e8-8819-de32f6ca7633.png)

And this is my experience using firefox 18.04

![screenshot from 2018-08-21 19-00-31](https://user-images.githubusercontent.com/928920/44438011-7017c800-a57a-11e8-9d61-16218909d146.png)

**Comment by fvsch** [comment]
@ilmoralito You probably mean Ubuntu 16.04 and Ubuntu 18.04?
It would be helpful to know the Firefox versions you’re using in both.
But, as said earlier, this should change in Firefox 63, you can test in Nightly if it works better for you.

**Comment by ilmoralito** [comment]
@fvsch upps, it's true, thanks for the clarification
